- project:
    promote:
      jobs:
        - dnf-copr-build

- secret:
    name: copr_secret
    data:
      data: !encrypted/pkcs1-oaep
        - r+F55cAWOrCOmrwUQ1l2rvzRYGqjkTVrg3HCo3Fh3LofTCeP9gUVZrNj/ME4RB4Gapx80
          LGTd7rD/SIexgGy7u52cbOsyAcKNxRJhAfPR4KJbLtDOF5dS0TTjll+IKH9gY/+qSWSQj
          YyZpJqhuRjO/nzQ4zlTEO/WJlgOjdGTc/3x5zj4KBFLa3VKXHOsx0TldyKO1OlgBczFO8
          zOxZLji6SdlUO3QFl4mtvvPmlMZ48zuK74y/grOhYekQbtB4IunADVn7vuy778jrR9VJS
          qTs0OHgcdC2MKED5oCcRbtjZT/qV/7FKH0WA9zvLecvs36zwLzqXxlfdjZ1gLG/7W642f
          h3d/2ThVM6pkT5VG1lguW9mApEE4zunG6HeaaFtAr54n9n847ppzmS7kQACac+ONILpCG
          5VE2YD5eP7xeVl9zjMRdxugGn4g1e+1jGCzgkCPuJw8Ml+T3Vbce0vbyE85LPOvCuuilI
          w8cs3alTvOLTCL344tAbtByG39mhOa5ZURCwwLvi6nca1ezfdQ15ZhmbyC4oBJfAklspa
          ftsINBg+slRlCbNGS0bnY3RyjLhxDYDGlMoqFu5a1HWo/OlBbQvm3KGHKLBYxJunwXvzl
          66wSmYe8aRrKwiqXScF9IS8qEvJgqluOO8quv5bO1IDyLfqC+gfiLebSLAQes8=

- job:
    name: dnf-copr-build
    description: Build package on the dnf-master COPR project a
    timeout: 5400
    roles:
      - zuul: zuul-distro-jobs
    secrets:
      - copr_secret
    vars:
      base_url: https://github.com
      reset_branch: true
      copr_repo: fbo/dnf-master-zuul-test
    run: playbooks/dnf-copr-build.yaml
    nodeset: fedora-30-vm
