- hosts: cloud-host
  vars:
    build_from_source: true
    version_from_specfile: true
    copr_retrieve_artifacts: false
  tasks:
    - include_role:
        name: copr-secret
    - fail:
        msg: test
#    - include_role:
#        name: source-to-tarball
#    - include_role:
#        name: simple-srpm-build
#    - include_role:
#        name: copr-build 
